# Generated by Django 4.1 on 2022-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0, max_length=100)),
                ('sex', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
