# Generated by Django 4.1 on 2022-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_test_bank_alter_test_age_alter_test_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
