# Generated by Django 4.1 on 2022-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_alter_test_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='bank',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
